name: Test


on:
  push:
    branches:
      - master

jobs:
  test: 
    name: Test
    runs-on: ubuntu-latest
    steps:

    -name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.19
      id: go
    
    -name: Check out code into the Go module directory.
      uses: actions/checkout@v2

    -name: Test
      run: make test 